name: fit_it
description: "Responsive widgets"
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  hooks_riverpod:
  modal_progress_hud_nsn:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
